In [1]:
import pandas as pd
import numpy as np
import re

import warnings
warnings.filterwarnings('ignore')

In [2]:
data_clean = pd.read_csv("data/EXPORT_SIPA_clean.csv")

In [3]:
def divide_lines(df, name):
    print(f"Procesando columna: {name}")
    
    if name not in df.columns:
        print(f"  ⚠️ Columna {name} no existe, saltando")
        return df
    
    if df[name].dtype != 'object':
        return df
    
    series = df[name]
    not_null_mask = series.notna()
    
    if not not_null_mask.any():
        return df
    
    has_strings = series[not_null_mask].apply(lambda x: isinstance(x, str)).any()
    if not has_strings:
        print(f"  ⚠️ Columna {name} no contiene strings, saltando")
        return df
    
    # Identificar qué filas tienen '||'
    has_separator = series.str.contains(r'\|\|', na=False)
    
    total_separators = series[has_separator].str.count(r'\|\|').sum()
    print(f"  Encontramos {total_separators} '||' en total")
    
    if total_separators == 0:
        return df
    
    # ✅ Solo dividir las filas que tienen '||'
    df.loc[has_separator, name] = series[has_separator].str.split(r'\|\|')
    
    print(f"  ✅ Columna {name} procesada exitosamente")
    return df

In [4]:
data_copy = data_clean.copy()
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,NaN,NaN,NaN,NaN,NaN,García Barsotti M.||Corbalán Herreros R.||Nazz...,NaN,NaN,...,Scopus||Pubmed,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,NaN,NaN,NaN,NaN,NaN,Mellado P.,NaN,NaN,...,Scopus,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,NaN,NaN,NaN,NaN,NaN,Vergara P.M.||Simonetti J.A.,NaN,NaN,...,Scopus,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,NaN,NaN,NaN,NaN,NaN,Gonzalez S.||Bolte C.||Bergman R.||Petronius D...,NaN,NaN,...,Scopus||Pubmed||WOS,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,NaN,NaN,Validado,NaN
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,NaN,NaN,NaN,NaN,NaN,Benítez N.||Ford H.||Menanteau F.||Blakeslee J...,NaN,NaN,...,Scopus||WOS,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,2025-01-27;55248;1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138912,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138913,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138914,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138915,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138916,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,NaN,NaN,carga,NaN,NaN,Juan A. Cañas||Daniel A. Bonilla||J. Bernal||A...,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;1070909;1

In [5]:
for col in data_copy.columns:
    data_copy = divide_lines(data_copy, col)

Procesando columna: id
  Encontramos 0 '||' en total
Procesando columna: collection
  Encontramos 0 '||' en total
Procesando columna: dc.article.number
  Encontramos 26 '||' en total
  ✅ Columna dc.article.number procesada exitosamente
Procesando columna: dc.cargado
  Encontramos 22 '||' en total
  ✅ Columna dc.cargado procesada exitosamente
Procesando columna: dc.catalogador
  Encontramos 14 '||' en total
  ✅ Columna dc.catalogador procesada exitosamente
Procesando columna: dc.concurso
  Encontramos 0 '||' en total
Procesando columna: dc.contributor.advisor
  Encontramos 1 '||' en total
  ✅ Columna dc.contributor.advisor procesada exitosamente
Procesando columna: dc.contributor.author
  Encontramos 2290809 '||' en total
  ✅ Columna dc.contributor.author procesada exitosamente
Procesando columna: dc.contributor.editor
  Encontramos 1323 '||' en total
  ✅ Columna dc.contributor.editor procesada exitosamente
Procesando columna: dc.contributor.illustrator
  Encontramos 0 '||' en total
Procesando columna: dc.contributor.other
  Encontramos 430 '||' en total
  ✅ Columna dc.contributor.other procesada exitosamente
Procesando columna: dc.contributor.participante
  Encontramos 1337 '||' en total
  ✅ Columna dc.contributor.participante procesada exitosamente
Procesando columna: dc.date
  Encontramos 0 '||' en total
Procesando columna: dc.date.accessioned
  Encontramos 0 '||' en total
Procesando columna: dc.date.available
  Encontramos 0 '||' en total
Procesando columna: dc.date.concesion
  Encontramos 0 '||' en total
Procesando columna: dc.date.created
  Encontramos 0 '||' en total
Procesando columna: dc.date.issued
Procesando columna: dc.date.updated
  Encontramos 0 '||' en total
Procesando columna: dc.description
  Encontramos 42 '||' en total
  ✅ Columna dc.description procesada exitosamente
Procesando columna: dc.description.abstract
  Encontramos 6818 '||' en total
  ✅ Columna dc.description.abstract procesada exitosamente
Procesando columna: dc.description.auspiciador
  Encontramos 223 '||' en total
  ✅ Columna dc.description.auspiciador procesada exitosamente
Procesando columna: dc.description.caracterobra
  Encontramos 0 '||' en total
Procesando columna: dc.description.funder
  Encontramos 65839 '||' en total
  ✅ Columna dc.description.funder procesada exitosamente
Procesando columna: dc.description.sponsorship
  Encontramos 200 '||' en total
  ✅ Columna dc.description.sponsorship procesada exitosamente
Procesando columna: dc.description.uri
  Encontramos 2 '||' en total
  ✅ Columna dc.description.uri procesada exitosamente
Procesando columna: dc.description.version
  Encontramos 0 '||' en total
Procesando columna: dc.estado.patente
  Encontramos 0 '||' en total
Procesando columna: dc.fechaingreso.objetodigital
  Encontramos 20 '||' en total
  ✅ Columna dc.fechaingreso.objetodigital procesada exitosamente
Procesando columna: dc.format
  Encontramos 0 '||' en total
Procesando columna: dc.format.extent
  Encontramos 46 '||' en total
  ✅ Columna dc.format.extent procesada exitosamente
Procesando columna: dc.format.medium
  Encontramos 0 '||' en total
Procesando columna: dc.fuente.origen
  Encontramos 555 '||' en total
  ✅ Columna dc.fuente.origen procesada exitosamente
Procesando columna: dc.identifier.UA
  Encontramos 1 '||' en total
  ✅ Columna dc.identifier.UA procesada exitosamente
Procesando columna: dc.identifier.citation
  Encontramos 2 '||' en total
  ✅ Columna dc.identifier.citation procesada exitosamente
Procesando columna: dc.identifier.codUA1
  Encontramos 3 '||' en total
  ✅ Columna dc.identifier.codUA1 procesada exitosamente
Procesando columna: dc.identifier.concesion
  Encontramos 0 '||' en total
Procesando columna: dc.identifier.converisid
Procesando columna: dc.identifier.dialnetid
  Encontramos 1 '||' en total
  ✅ Columna dc.identifier.dialnetid procesada exitosamente
Procesando columna: dc.identifier.doi
  Encontramos 47 '||' en total
  ✅ Columna dc.identifier.doi procesada exitosamente
Procesando columna: dc.identifier.eisbn
  Encontramos 19 '||' en total
  ✅ Columna dc.identifier.eisbn procesada exitosamente
Procesando columna: dc.identifier.eissn
  Encontramos 37 '||' en total
  ✅ Columna dc.identifier.eissn procesada exitosamente
Procesando columna: dc.identifier.govdoc
  Encontramos 0 '||' en total
Procesando columna: dc.identifier.isbn
  Encontramos 129 '||' en total
  ✅ Columna dc.identifier.isbn procesada exitosamente
Procesando columna: dc.identifier.issn
  Encontramos 201 '||' en total
  ✅ Columna dc.identifier.issn procesada exitosamente
Procesando columna: dc.identifier.other
  Encontramos 0 '||' en total
Procesando columna: dc.identifier.pubmedid
  Encontramos 45 '||' en total
  ✅ Columna dc.identifier.pubmedid procesada exitosamente
Procesando columna: dc.identifier.scieloid
  Encontramos 0 '||' en total
Procesando columna: dc.identifier.scopusid
  Encontramos 1 '||' en total
  ✅ Columna dc.identifier.scopusid procesada exitosamente
Procesando columna: dc.identifier.uri
  Encontramos 88888 '||' en total
  ✅ Columna dc.identifier.uri procesada exitosamente
Procesando columna: dc.identifier.wosid
  Encontramos 0 '||' en total
Procesando columna: dc.information.autoruc
  Encontramos 57954 '||' en total
  ✅ Columna dc.information.autoruc procesada exitosamente
Procesando columna: dc.issue.numero
  Encontramos 24 '||' en total
  ✅ Columna dc.issue.numero procesada exitosamente
Procesando columna: dc.language
  Encontramos 0 '||' en total
Procesando columna: dc.language.iso
  Encontramos 121 '||' en total
  ✅ Columna dc.language.iso procesada exitosamente
Procesando columna: dc.lugar.publicacion
  Encontramos 21 '||' en total
  ✅ Columna dc.lugar.publicacion procesada exitosamente
Procesando columna: dc.nota.acceso
  Encontramos 23 '||' en total
  ✅ Columna dc.nota.acceso procesada exitosamente
Procesando columna: dc.pagina.final
  Encontramos 37 '||' en total
  ✅ Columna dc.pagina.final procesada exitosamente
Procesando columna: dc.pagina.inicio
  Encontramos 21 '||' en total
  ✅ Columna dc.pagina.inicio procesada exitosamente
Procesando columna: dc.pais
  Encontramos 1 '||' en total
  ✅ Columna dc.pais procesada exitosamente
Procesando columna: dc.presentacion
  Encontramos 0 '||' en total
Procesando columna: dc.publisher
  Encontramos 154 '||' en total
  ✅ Columna dc.publisher procesada exitosamente
Procesando columna: dc.relation
  Encontramos 0 '||' en total
Procesando columna: dc.relation.isformatof
  Encontramos 4 '||' en total
  ✅ Columna dc.relation.isformatof procesada exitosamente
Procesando columna: dc.relation.ispartof
  Encontramos 29 '||' en total
  ✅ Columna dc.relation.ispartof procesada exitosamente
Procesando columna: dc.relation.ispartofseries
  Encontramos 12 '||' en total
  ✅ Columna dc.relation.ispartofseries procesada exitosamente
Procesando columna: dc.relation.uri
  Encontramos 0 '||' en total
Procesando columna: dc.revista[es_ES]
  Encontramos 59 '||' en total
  ✅ Columna dc.revista[es_ES] procesada exitosamente
Procesando columna: dc.rights
  Encontramos 0 '||' en total
Procesando columna: dc.rights.holder
  Encontramos 0 '||' en total
Procesando columna: dc.rights.license
  Encontramos 8 '||' en total
  ✅ Columna dc.rights.license procesada exitosamente
Procesando columna: dc.rights.spa
  Encontramos 4 '||' en total
  ✅ Columna dc.rights.spa procesada exitosamente
Procesando columna: dc.rights.uri
  Encontramos 1 '||' en total
  ✅ Columna dc.rights.uri procesada exitosamente
Procesando columna: dc.rol
  Encontramos 1349 '||' en total
  ✅ Columna dc.rol procesada exitosamente
Procesando columna: dc.solicitante
  Encontramos 5 '||' en total
  ✅ Columna dc.solicitante procesada exitosamente
Procesando columna: dc.subject.classification
  Encontramos 6 '||' en total
  ✅ Columna dc.subject.classification procesada exitosamente
Procesando columna: dc.subject.ddc
  Encontramos 37 '||' en total
  ✅ Columna dc.subject.ddc procesada exitosamente
Procesando columna: dc.subject.dewey[es_ES]
  Encontramos 3 '||' en total
  ✅ Columna dc.subject.dewey[es_ES] procesada exitosamente
Procesando columna: dc.subject.ods
  Encontramos 6131 '||' en total
  ✅ Columna dc.subject.ods procesada exitosamente
Procesando columna: dc.subject.odspa
  Encontramos 6131 '||' en total
  ✅ Columna dc.subject.odspa procesada exitosamente
Procesando columna: dc.subject.other[es_ES]
  Encontramos 19182 '||' en total
  ✅ Columna dc.subject.other[es_ES] procesada exitosamente
Procesando columna: dc.subject[es_ES]
  Encontramos 209160 '||' en total
  ✅ Columna dc.subject[es_ES] procesada exitosamente
Procesando columna: dc.territorialidad
  Encontramos 0 '||' en total
Procesando columna: dc.tipodeobra
  Encontramos 3 '||' en total
  ✅ Columna dc.tipodeobra procesada exitosamente
Procesando columna: dc.title
  Encontramos 20 '||' en total
  ✅ Columna dc.title procesada exitosamente
Procesando columna: dc.title.alternative[es_ES]
  Encontramos 494 '||' en total
  ✅ Columna dc.title.alternative[es_ES] procesada exitosamente
Procesando columna: dc.title[es_ES]
  Encontramos 20 '||' en total
  ✅ Columna dc.title[es_ES] procesada exitosamente
Procesando columna: dc.type
  Encontramos 46 '||' en total
  ✅ Columna dc.type procesada exitosamente
Procesando columna: dc.types.oa
  Encontramos 0 '||' en total
Procesando columna: dc.ubicacion
  Encontramos 183 '||' en total
  ✅ Columna dc.ubicacion procesada exitosamente
Procesando columna: dc.volumen
  Encontramos 28 '||' en total
  ✅ Columna dc.volumen procesada exitosamente
Procesando columna: dcterms.eissn
  Encontramos 0 '||' en total
Procesando columna: sipa.DynamicData
  Encontramos 0 '||' en total
Procesando columna: sipa.StaticData
  Encontramos 0 '||' en total
Procesando columna: sipa.WOS_Dates
  Encontramos 0 '||' en total
Procesando columna: sipa.afi.uc
  Encontramos 7 '||' en total
  ✅ Columna sipa.afi.uc procesada exitosamente
Procesando columna: sipa.autores_UC
  Encontramos 2 '||' en total
  ✅ Columna sipa.autores_UC procesada exitosamente
Procesando columna: sipa.codpersvinculados
  Encontramos 84121 '||' en total
  ✅ Columna sipa.codpersvinculados procesada exitosamente
Procesando columna: sipa.fecha.validacionbiblio
  Encontramos 103 '||' en total
  ✅ Columna sipa.fecha.validacionbiblio procesada exitosamente
Procesando columna: sipa.fecha.validavinculacion
  Encontramos 291 '||' en total
  ✅ Columna sipa.fecha.validavinculacion procesada exitosamente
Procesando columna: sipa.fecha.vinculacion
  Encontramos 68720 '||' en total
  ✅ Columna sipa.fecha.vinculacion procesada exitosamente
Procesando columna: sipa.fechainicio
  Encontramos 7 '||' en total
  ✅ Columna sipa.fechainicio procesada exitosamente
Procesando columna: sipa.fechatermino
  Encontramos 4 '||' en total
  ✅ Columna sipa.fechatermino procesada exitosamente
Procesando columna: sipa.identificadores
  Encontramos 105977 '||' en total
  ✅ Columna sipa.identificadores procesada exitosamente
Procesando columna: sipa.identifier.ha
  Encontramos 238 '||' en total
  ✅ Columna sipa.identifier.ha procesada exitosamente
Procesando columna: sipa.identifier.hacreacionartistica
  Encontramos 11 '||' en total
  ✅ Columna sipa.identifier.hacreacionartistica procesada exitosamente
Procesando columna: sipa.identifier.repositoriouc
  Encontramos 0 '||' en total
Procesando columna: sipa.identifier.solicpropintelectual
  Encontramos 0 '||' en total
Procesando columna: sipa.index
  Encontramos 84563 '||' en total
  ✅ Columna sipa.index procesada exitosamente
Procesando columna: sipa.revision
  Encontramos 0 '||' en total
Procesando columna: sipa.tipocreacion
  Encontramos 3 '||' en total
  ✅ Columna sipa.tipocreacion procesada exitosamente
Procesando columna: sipa.trazabilidad
  Encontramos 17345 '||' en total
  ✅ Columna sipa.trazabilidad procesada exitosamente
Procesando columna: sipa.type.local
  Encontramos 0 '||' en total
Procesando columna: sipa.validacionbiblio
  Encontramos 8 '||' en total
  ✅ Columna sipa.validacionbiblio procesada exitosamente
Procesando columna: sipa.validacionods
  Encontramos 0 '||' en total
Procesando columna: sipa.validacionrights
  Encontramos 0 '||' en total
Procesando columna: sipa.validacionsipa
  Encontramos 0 '||' en total
Procesando columna: sipa.vinculacionsipa
  Encontramos 59290 '||' en total
  ✅ Columna sipa.vinculacionsipa procesada exitosamente

In [6]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,NaN,NaN,NaN,NaN,NaN,"[García Barsotti M., Corbalán Herreros R., Naz...",NaN,NaN,...,"[Scopus, Pubmed]",Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,NaN,NaN,NaN,NaN,NaN,Mellado P.,NaN,NaN,...,Scopus,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,NaN,NaN,NaN,NaN,NaN,"[Vergara P.M., Simonetti J.A.]",NaN,NaN,...,Scopus,Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,NaN
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,NaN,NaN,NaN,NaN,NaN,"[Gonzalez S., Bolte C., Bergman R., Petronius ...",NaN,NaN,...,"[Scopus, Pubmed, WOS]",Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,NaN,NaN,Validado,NaN
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,NaN,NaN,NaN,NaN,NaN,"[Benítez N., Ford H., Menanteau F., Blakeslee ...",NaN,NaN,...,"[Scopus, WOS]",Sin revisión,NaN,Scopus;12-10-2021,NaN,Sin validar,OSDG;2025-12-22,NaN,Validado,2025-01-27;55248;1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138912,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138913,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138914,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138915,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,NaN,NaN,carga,NaN,NaN,Jose Tomas Alvarado,NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;90223;1
138916,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,NaN,NaN,carga,NaN,NaN,"[Juan A. Cañas, Daniel A. Bonilla, J. Bernal, ...",NaN,NaN,...,NaN,NaN,NaN,ORCID;2026-05-25,NaN,Sin validar,NaN,NaN,Validado,2026-05-25;1070909;1

In [7]:
def clean_nan(val):
    """
    Limpia valores NaN, None, listas y strings con separadores mixtos.
    """
    # 1. Manejar explícitamente listas, dicts, arrays, etc.
    if isinstance(val, (list, dict, np.ndarray)):
        return val  # los dejamos intactos
    
    # 2. Manejar nulos escalares
    try:
        if pd.isna(val):
            return "No hay registro"
    except (ValueError, TypeError):
        pass 
    
    # 3. Siempre retornar el valor original si no es nulo
    return val

In [8]:
for col in data_copy.columns:
   data_copy[col] = data_copy[col].apply(clean_nan)

In [9]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,"[García Barsotti M., Corbalán Herreros R., Naz...",No hay registro,No hay registro,...,"[Scopus, Pubmed]",Sin revisión,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,Mellado P.,No hay registro,No hay registro,...,Scopus,Sin revisión,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,"[Vergara P.M., Simonetti J.A.]",No hay registro,No hay registro,...,Scopus,Sin revisión,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,"[Gonzalez S., Bolte C., Bergman R., Petronius ...",No hay registro,No hay registro,...,"[Scopus, Pubmed, WOS]",Sin revisión,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,No hay registro,No hay registro,Validado,No hay registro
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,"[Benítez N., Ford H., Menanteau F., Blakeslee ...",No hay registro,No hay registro,...,"[Scopus, WOS]",Sin revisión,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,2025-01-27;55248;1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138912,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
138913,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
138914,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
138915,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
138916,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,"[Juan A. Cañas, Daniel A. Bonilla, J. Bernal, ...",No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;1070909;1