In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_clean = pd.read_csv("data/EXPORT_SIPA_clean.csv")

In [3]:
def keep_paired_items(items):
    item_set = set(items)
    filtered = []
    
    for item in items:
        if item.endswith('[]'):
            base_name = item[:-2]
            if base_name in item_set:
                filtered.append(item)
        else:
            bracket_version = item + '[]'
            if bracket_version in item_set:
                filtered.append(item)
                
    return filtered

In [4]:
def combine_columns(df):
    cols = df.columns.tolist()
    bracket_cols = [c for c in cols if c.endswith('[]')]
    
    for b_col in bracket_cols:
        base_name = b_col[:-2] 
        
        if base_name in cols:
            
            col_base = df[base_name].astype(str).replace('nan', '')
            col_brack = df[b_col].astype(str).replace('nan', '')
            
            combined = []
            for b, k in zip(col_base, col_brack):
                if b and k:
                    combined.append(f"{b};{k}")
                elif b:
                    combined.append(b)
                elif k:
                    combined.append(k)
                else:
                    combined.append('')
                    
            df[base_name] = combined
            df.drop(columns=[b_col], inplace=True) 
            
    return df

In [5]:
def divide_lines(df, name):
    counts = df[name].str.count(r'\|\|')
    
    conditions = [
        counts == 1,   
        counts > 1     
    ]
    choices = [
        df[name].str.replace(r'\|\|', ', ', regex=False),         
        df[name].str.split(r'\|\|')
    ]
    
    df[name] = np.select(conditions, choices, default=df[name])
    
    return df

In [49]:
data_copy = data_clean.copy()
data_copy = combine_columns(data_copy)

In [40]:
columns_to_divide = [
    "dc.contributor.author",
    "dc.contributor.advisor",
    "dc.contributor.editor",
    "dc.date.concesion",
    "dc.date.created"
]

In [41]:
for col in columns_to_divide:
    data_copy = divide_lines(data_copy, col)

In [42]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[GarcÃ­a Barsotti M., CorbalÃ¡n Herreros R., N...",nan;nan,nan;nan,...,Scopus||Pubmed;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,Mellado P.;nan,nan;nan,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[Vergara P.M., Simonetti J.A., Vergara P.M.;nan]",nan;nan,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[Gonzalez S., Bolte C., Bergman R., Petronius ...",nan;nan,nan;nan,...,Scopus||Pubmed||WOS;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,nan;nan
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[BenÃ­tez N., Ford H., Menanteau F., Blakeslee...",nan;nan,nan;nan,...,Scopus||WOS;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,2025-01-27;55248;1;nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139683,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139684,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139685,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139686,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139687,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,"[Juan A. CaÃ±as, Daniel A. Bonilla, J. Bernal,...",nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;1070909;1;nan

In [50]:
import pandas as pd
import numpy as np
import re

def clean_mixed_types_v2(val):
    """
    Handles strings, lists, arrays.
    Splits by BOTH ';' and '||'.
    Removes 'nan' entries.
    """
    
    # 1. Handle List or NumPy Array
    if isinstance(val, (list, np.ndarray)):
        if isinstance(val, np.ndarray):
            val = val.tolist()
        
        cleaned_items = []
        for item in val:
            try:
                if pd.isna(item): continue
            except: continue
            
            # Process each item recursively in case it contains separators
            s = str(item).strip()
            parts = re.split(r';|\|\|', s) # Split by ; OR ||
            
            for p in parts:
                p_clean = p.strip()
                if p_clean.lower() != 'nan' and p_clean != '':
                    cleaned_items.append(p_clean)
                    
        if not cleaned_items:
            return "No hay registro"
        return ';'.join(cleaned_items) # Standardize output to use semicolon

    # 2. Handle Scalar NaN
    try:
        if pd.isna(val):
            return "No hay registro"
    except: pass

    # 3. Handle String/Number
    try:
        s = str(val).strip()
        if s.lower() == 'nan':
            return "No hay registro"
            
        # Split by EITHER ; OR ||
        parts = re.split(r';|\|\|', s)
        
        filtered = [p.strip() for p in parts if p.strip().lower() != 'nan' and p.strip() != '']
        
        if not filtered:
            return "No hay registro"
            
        # Return joined by semicolon for consistency
        return ';'.join(filtered)
        
    except Exception:
        return "No hay registro"

# Apply cleaning
for col in columns_to_divide:
    print(f"Cleaning column: {col}")
    data_copy[col] = data_copy[col].apply(clean_mixed_types_v2)
    
    # Now divide_lines should work because all cells are simple strings
    print(f"Dividing lines for: {col}")
    data_copy = divide_lines(data_copy, col)

Cleaning column: dc.contributor.author
Dividing lines for: dc.contributor.author
Cleaning column: dc.contributor.advisor
Dividing lines for: dc.contributor.advisor
Cleaning column: dc.contributor.editor
Dividing lines for: dc.contributor.editor
Cleaning column: dc.date.concesion
Dividing lines for: dc.date.concesion
Cleaning column: dc.date.created
Dividing lines for: dc.date.created

In [51]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,No hay registro,GarcÃ­a Barsotti M.;CorbalÃ¡n Herreros R.;Nazz...,No hay registro,nan;nan,...,Scopus||Pubmed;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,No hay registro,Mellado P.,No hay registro,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,No hay registro,Vergara P.M.;Simonetti J.A.;Vergara P.M.,No hay registro,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,No hay registro,Gonzalez S.;Bolte C.;Bergman R.;Petronius D.;S...,No hay registro,nan;nan,...,Scopus||Pubmed||WOS;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,nan;nan
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,No hay registro,BenÃ­tez N.;Ford H.;Menanteau F.;Blakeslee J.;...,No hay registro,nan;nan,...,Scopus||WOS;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,2025-01-27;55248;1;nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139683,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,No hay registro,Jose Tomas Alvarado,No hay registro,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139684,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,No hay registro,Jose Tomas Alvarado,No hay registro,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139685,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,No hay registro,Jose Tomas Alvarado,No hay registro,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139686,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,No hay registro,Jose Tomas Alvarado,No hay registro,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139687,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,No hay registro,Juan A. CaÃ±as;Daniel A. Bonilla;J. Bernal;A. ...,No hay registro,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;1070909;1;nan

In [24]:
def procesar_valor_simple(valor):
    # Dividir por ";"
    partes = str(valor).split(';')
    
    # Eliminar TODOS los "nan" de la lista
    partes_limpias = [p for p in partes if p != 'nan']
    
    # Si quedó vacío, retornar "No registrado"
    if not partes_limpias:
        return 'No registrado'
    
    # Unir con ";"
    return ';'.join(partes_limpias)

In [25]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[GarcÃ­a Barsotti M., CorbalÃ¡n Herreros R., N...",nan;nan,nan;nan,...,Scopus||Pubmed;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,Mellado P.;nan,nan;nan,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[Vergara P.M., Simonetti J.A., Vergara P.M.;nan]",nan;nan,nan;nan,...,Scopus;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,nan;nan
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[Gonzalez S., Bolte C., Bergman R., Petronius ...",nan;nan,nan;nan,...,"[Scopus, Pubmed, WOS;nan]",Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,nan;nan
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,nan;nan,nan;nan,nan;nan,nan;nan,NaN,"[BenÃ­tez N., Ford H., Menanteau F., Blakeslee...",nan;nan,nan;nan,...,Scopus||WOS;nan,Sin revisiÃ³n;nan,nan;nan,Scopus;12-10-2021;nan,NaN,Sin validar;nan,OSDG;2025-12-22;nan,nan;nan,Validado;nan,2025-01-27;55248;1;nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139683,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139684,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139685,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139686,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,Jose Tomas Alvarado;nan,nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;90223;1;nan
139687,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,nan;nan,nan;nan,carga;nan,nan;nan,NaN,"[Juan A. CaÃ±as, Daniel A. Bonilla, J. Bernal,...",nan;nan,nan;nan,...,nan;nan,nan;nan,nan;nan,ORCID;2026-05-25;nan,NaN,Sin validar;nan,nan;nan,nan;nan,Validado;nan,2026-05-25;1070909;1;nan

In [52]:
def clean_nan_values_ultimate(val):
    # 1. Handle actual pandas NaN / None values
    # We use a try-except here because pd.isna() can fail on arrays/lists in some versions
    try:
        if pd.isna(val):
            return "No hay registro"
    except (ValueError, TypeError):
        pass # If it fails, we assume it's not a simple scalar NaN and proceed to check type

    # 2. Handle Lists and NumPy Arrays
    if isinstance(val, (list, np.ndarray)):
        # Convert to list if it's an array
        if isinstance(val, np.ndarray):
            val = val.tolist()
        
        # Filter out 'nan', None, and empty strings
        filtered = []
        for item in val:
            # Handle cases where the item inside the list might also be NaN
            if pd.isna(item):
                continue
            s = str(item).strip()
            if s.lower() != 'nan' and s != '':
                filtered.append(s)
                
        if not filtered:
            return "No hay registro"
        return ';'.join(filtered)

    # 3. Handle Standard Strings/Numbers
    try:
        val_str = str(val)
        parts = val_str.split(';')
        
        filtered_parts = [
            p.strip() for p in parts 
            if p.strip().lower() != 'nan' and p.strip() != ''
        ]
        
        if not filtered_parts:
            return "No hay registro"
            
        return ';'.join(filtered_parts)
        
    except Exception as e:
        # Last resort fallback
        return f"Error: {type(val)}"

In [53]:
# Apply to your column
data_copy["dc.article.number"] = data_copy["dc.article.number"].apply(clean_nan_values_ultimate)

In [54]:
data_copy["dc.cargado"] = data_copy["dc.cargado"].apply(clean_nan_values_ultimate)

In [55]:
data_copy["dc.cargado"] = data_copy["dc.cargado"].apply(clean_nan_values_ultimate)

In [56]:
# Apply to your column
data_copy["dc.catalogador"] = data_copy["dc.catalogador"].apply(clean_nan_values_ultimate)

In [57]:
# Apply to your column
data_copy["dc.concurso"] = data_copy["dc.concurso"].apply(clean_nan_values_ultimate)

In [59]:
for col in data_copy.columns:
   data_copy[col] = data_copy[col].apply(clean_nan_values_ultimate)

In [ ]:
data_copy["dc.fechaingreso"] = data_copy["dc.fechaingreso"].

In [60]:
data_copy

,id,collection,dc.article.number,dc.cargado,dc.catalogador,dc.concurso,dc.contributor.advisor,dc.contributor.author,dc.contributor.editor,dc.contributor.illustrator,...,sipa.index,sipa.revision,sipa.tipocreacion,sipa.trazabilidad,sipa.type.local,sipa.validacionbiblio,sipa.validacionods,sipa.validacionrights,sipa.validacionsipa,sipa.vinculacionsipa
0,e79eaebd-354a-4801-ae8c-4f1ab1969a8e,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,GarcÃ­a Barsotti M.;CorbalÃ¡n Herreros R.;Nazz...,No hay registro,No hay registro,...,Scopus||Pubmed,Sin revisiÃ³n,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
1,ba6125bb-edee-47b1-b84d-6fd62a288b63,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,Mellado P.,No hay registro,No hay registro,...,Scopus,Sin revisiÃ³n,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
2,6f6c3642-afe7-4173-830b-8302d2a2472c,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,Vergara P.M.;Simonetti J.A.;Vergara P.M.,No hay registro,No hay registro,...,Scopus,Sin revisiÃ³n,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,No hay registro
3,ac4b2bf0-b63c-4ed4-a794-038f23e9acbc,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,Gonzalez S.;Bolte C.;Bergman R.;Petronius D.;S...,No hay registro,No hay registro,...,Scopus||Pubmed||WOS,Sin revisiÃ³n,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,No hay registro,No hay registro,Validado,No hay registro
4,f19e026f-3104-44d2-b248-35b3c5493d35,123456789/2,No hay registro,No hay registro,No hay registro,No hay registro,No hay registro,BenÃ­tez N.;Ford H.;Menanteau F.;Blakeslee J.;...,No hay registro,No hay registro,...,Scopus||WOS,Sin revisiÃ³n,No hay registro,Scopus;12-10-2021,No hay registro,Sin validar,OSDG;2025-12-22,No hay registro,Validado,2025-01-27;55248;1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139683,41cab66e-435d-494b-8177-1dc1625385da,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
139684,5b1ab0df-713a-4a00-85af-773ad3c54625,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
139685,92172233-4c06-4f16-b5d2-4e472015d1b0,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
139686,27402dfc-a6cf-4b0a-87d2-e423365c42dd,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Jose Tomas Alvarado,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;90223;1
139687,27d8ea41-6124-47f4-b95d-4e493fe097e8,123456789/2,No hay registro,No hay registro,carga,No hay registro,No hay registro,Juan A. CaÃ±as;Daniel A. Bonilla;J. Bernal;A. ...,No hay registro,No hay registro,...,No hay registro,No hay registro,No hay registro,ORCID;2026-05-25,No hay registro,Sin validar,No hay registro,No hay registro,Validado,2026-05-25;1070909;1